export const FETCH_PLACES = 'FETCH_PLACES';

export const CREATE_PLACE= 'CREATE_PLACE';

export const UPDATE_PLACE= 'UPDATE_PLACE';

export const DELETE_PLACE= 'DELETE_PLACE';

export const ERROR_IN_PLACES = 'ERROR_IN_PLACES';